### ISSUE TITLE
Error reading AWS  keys from Kube Secrets

### ISSUE THREAD

**Issue by preflightsiren** [openai/kubernetes-ec2-autoscaler#14]
I was trialing the autoscaler on kube 1.4.5 with the below yml

```
---
apiVersion: v1
kind: Secret
metadata:
  name: autoscaler
  namespace: kube-system
data:
  aws-access-key-id: access_key==
  aws-secret-access-key: secret_key==

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: autoscaler
  namespace: kube-system
spec:
  replicas: 1
  selector:
    app: autoscaler
  template:
    metadata:
      labels:
        app: autoscaler
    spec:
      containers:
      - name: autoscaler
        image: quay.io/openai/kubernetes-ec2-autoscaler
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: autoscaler
              key: aws-access-key-id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: autoscaler
              key: aws-secret-access-key
        - name: SLACK_HOOK
          valueFrom:
            secretKeyRef:
              name: autoscaler
              key: slack-hook
        - name: DATADOG_API_KEY
          valueFrom:
            secretKeyRef:
              name: autoscaler
              key: datadog-api-key
        - name: PYKUBE_KUBERNETES_SERVICE_HOST
          value: 10.100.0.1
          # value: kubernetes.default
        - name: DATADOG_TAGS
          value: env:sci
        command:
            - python
            - main.py
            - --regions
            - us-east-1
            - --cluster-name
            - mycluster
            - -vvv
            - --type-idle-threshold
            - "0"
            - --sleep
            - "30"
        imagePullPolicy: Always
      restartPolicy: Always
      dnsPolicy: Default  # Don't use cluster DNS.
      nodeSelector:
        failure-domain.beta.kubernetes.io/region: us-east-1
```
Which resulted in an exception trying to read the autoscaling groups from AWS. The important line is (note the \n after the access_key) 

```
2016-11-07T00:39:05.474192012Z ValueError: Invalid header value 'AWS4-HMAC-SHA256 Credential=access_key\n/20161107/us-east-1/ec2/aws4_request, SignedHeaders=host;x-amz-date, Signature=xxxxxxxxxxx'
```

not sure if this is a change to the secrets mechanism in kube, or the app. I changed the ReplicationController resource to have the environment values explicitly defined within spec.containers.env[] and it worked as expected.
