### ISSUE TITLE
Failing to start ReplicationController

### ISSUE THREAD

**Issue by ziyasal** [openai/kubernetes-ec2-autoscaler#20]
Hi, thank you for this project!
I got some issues while setting up autoscaler, here are details;

## Problem
I am getting an error while trying to create `ReplicationController`; 
```sh
pod (autoscaler-xxxx) failed to fit in any node fit failure 
summary on nodes : MatchNodeSelector (4)
```

## System Details

```sh
kubectl version --short

# Output
Client Version: v1.5.2
Server Version: v1.5.2
```

## My Setup
**secret.yaml**
```
apiVersion: v1
kind: Secret
metadata:
  name: autoscaler
  namespace:system
data:
  aws-access-key-id:[base64]
  aws-secret-access-key:[base64]
```

**controller.yaml**
```yaml
apiVersion: v1
kind: ReplicationController
metadata:
  name: autoscaler
  namespace: system
spec:
  replicas: 1
  selector:
    app: autoscaler
  template:
    metadata:
      labels:
        app: autoscaler
        openai/do-not-drain: "true"
    spec:
      containers:
      - name: autoscaler
        image: quay.io/openai/kubernetes-ec2-autoscaler
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: autoscaler
              key: aws-access-key-id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: autoscaler
              key: aws-secret-access-key
        - name: PYKUBE_KUBERNETES_SERVICE_HOST
          value: [master-node-ip]
          # value: kubernetes.default
        command:
            - python
            - main.py
            - --regions
            - us-west-2
            - --cluster-name
            - [cluster_name]
            - -vvv
            - --type-idle-threshold
            - "0"
            - --over-provision
            - "1"
            - --sleep
            - "30"
        imagePullPolicy: Always
      restartPolicy: Always
      dnsPolicy: Default
      nodeSelector:
        aws/region: us-west-2
```

Thx.
