### ISSUE TITLE
Error about no schedule taints when startup

### ISSUE THREAD

**Issue by opstacloud** [openai/kubernetes-ec2-autoscaler#90]
Raw logging from pod
```
2018-02-13T16:25:11+0000 - autoscaler.cluster - DEBUG - Using kube service account
2018-02-13T16:25:11+0000 - autoscaler.cluster - INFO - ++++++++++++++ Running Scaling Loop ++++++++++++++++
Traceback (most recent call last):
  File "main.py", line 111, in <module>
    main()
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "main.py", line 100, in main
    scaled = cluster.scale_loop()
  File "/app/autoscaler/cluster.py", line 195, in scale_loop
    all_nodes = list(map(KubeNode, pykube_nodes))
  File "/app/autoscaler/kube.py", line 156, in __init__
    self.no_schedule_taints[taint['key']] = taint['value']
KeyError: 'value'
```

Taints and Labels
```
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/instance-type=t2.medium
                    beta.kubernetes.io/os=linux
                    failure-domain.beta.kubernetes.io/region=ap-southeast-1
                    failure-domain.beta.kubernetes.io/zone=ap-southeast-1a
                    kops.k8s.io/instancegroup=master-ap-southeast-1a
                    kubernetes.io/hostname=ip-xx.xx.xx.xx.ap-southeast-1.compute.internal
                    kubernetes.io/role=master
                    node-role.kubernetes.io/master=
Annotations:        node.alpha.kubernetes.io/ttl=0
                    volumes.kubernetes.io/controller-managed-attach-detach=true
Taints:             node-role.kubernetes.io/master:NoSchedule
```

Deployment YAML
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: autoscaler
  namespace: kube-system
  labels:
    k8s-app: autoscaler
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: autoscaler
  template:
    metadata:
      labels:
        k8s-app: autoscaler
        openai/do-not-drain: "true"
        kubernetes.io/cluster-service: "true"
    #annotations:
     # scheduler.alpha.kubernetes.io/tolerations: "[{key: dedicated, value: master}]"
    spec:
      containers:
      - name: autoscaler
        image: quay.io/openai/kubernetes-ec2-autoscaler
        resources:
          limits:
            cpu: 500m
            memory: 300Mi
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: CAPACITY_CPU_RESERVE
          value: "0.1"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: autoscaler
              key: aws-access-key-id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: autoscaler
              key: aws-secret-access-key
        # - name: SLACK_HOOK
        #   valueFrom:
        #     secretKeyRef:
        #       name: autoscaler
        #       key: slack-hook
        # - name: SLACK_BOT_TOKEN
        #   valueFrom:
        #     secretKeyRef:
        #       name: autoscaler
        #       key: slack-bot-token
        # - name: DATADOG_API_KEY
        #   valueFrom:
        #     secretKeyRef:
        #       name: autoscaler
        #       key: datadog-api-key
        - name: PYKUBE_KUBERNETES_SERVICE_HOST
          value: 10.100.0.1
        # - name: DATADOG_TAGS
        #   value: env:sci
        command:
            - python
            - main.py
            - --aws-regions
            - ap-southeast-1
            - --cluster-name
            - cluster-name.k8s.local
            - -vvv
            - --type-idle-threshold
            - "0"
            # - --over-provision
            # - "1"
            - --sleep
            - "30"
        imagePullPolicy: Always
      restartPolicy: Always
      dnsPolicy: Default  # Don't use cluster DNS.
      nodeSelector:
        node-role.kubernetes.io/master: ""
        # kubernetes.io/role: master

```

I try with both of kubernetes version 1.7.1 and 1.8.8 but it's not work

More detail
- Deploy Kubernetes cluster with kops
